name: wait_med
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.1

  # Maps & Location
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2

  # Networking
  http: ^1.5.0

  # State Management
  get: ^4.7.2

  # Location + Notifications
  flutter_local_notifications: ^17.0.0
  geofence_service: 6.0.0+1
  permission_handler: ^11.0.1

  # login
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
